// Shared USDA Plant Hardiness Zone + frost-date estimation logic.
//
// This module is the single source of truth for zone-based frost date
// estimation, used by both the Frost Date Calculator and the Seed Starting
// Calculator so the two tools stay in sync — the seed starting calendar is
// built directly on top of these same frost date estimates, not a separate
// system with its own (possibly drifting) numbers.

// ---------------------------------------------------------------------------
// ZIP3 prefix -> state mapping. This is the standard, publicly documented USPS
// ZIP code allocation by state (the same ranges published in USPS/Wikipedia
// ZIP-prefix references) — deterministic and accurate at the state level, not
// an estimate. Territories and a handful of unused prefixes are omitted; a ZIP
// that doesn't resolve just falls through to "not found."
// ---------------------------------------------------------------------------
export interface Zip3Range {
  start: number;
  end: number;
  state: string;
}

export const ZIP3_TO_STATE: Zip3Range[] = [
  { start: 10, end: 27, state: 'MA' },
  { start: 28, end: 29, state: 'RI' },
  { start: 30, end: 38, state: 'NH' },
  { start: 39, end: 49, state: 'ME' },
  { start: 50, end: 59, state: 'VT' },
  { start: 60, end: 69, state: 'CT' },
  { start: 70, end: 89, state: 'NJ' },
  { start: 100, end: 149, state: 'NY' },
  { start: 150, end: 196, state: 'PA' },
  { start: 197, end: 199, state: 'DE' },
  { start: 200, end: 205, state: 'DC' },
  { start: 206, end: 219, state: 'MD' },
  { start: 220, end: 246, state: 'VA' },
  { start: 247, end: 268, state: 'WV' },
  { start: 270, end: 289, state: 'NC' },
  { start: 290, end: 299, state: 'SC' },
  { start: 300, end: 319, state: 'GA' },
  { start: 320, end: 349, state: 'FL' },
  { start: 350, end: 369, state: 'AL' },
  { start: 370, end: 385, state: 'TN' },
  { start: 386, end: 397, state: 'MS' },
  { start: 398, end: 399, state: 'GA' },
  { start: 400, end: 427, state: 'KY' },
  { start: 430, end: 459, state: 'OH' },
  { start: 460, end: 479, state: 'IN' },
  { start: 480, end: 499, state: 'MI' },
  { start: 500, end: 528, state: 'IA' },
  { start: 530, end: 549, state: 'WI' },
  { start: 550, end: 567, state: 'MN' },
  { start: 570, end: 577, state: 'SD' },
  { start: 580, end: 588, state: 'ND' },
  { start: 590, end: 599, state: 'MT' },
  { start: 600, end: 629, state: 'IL' },
  { start: 630, end: 658, state: 'MO' },
  { start: 660, end: 679, state: 'KS' },
  { start: 680, end: 693, state: 'NE' },
  { start: 700, end: 714, state: 'LA' },
  { start: 716, end: 729, state: 'AR' },
  { start: 730, end: 749, state: 'OK' },
  { start: 750, end: 799, state: 'TX' },
  { start: 800, end: 816, state: 'CO' },
  { start: 820, end: 831, state: 'WY' },
  { start: 832, end: 838, state: 'ID' },
  { start: 840, end: 847, state: 'UT' },
  { start: 850, end: 865, state: 'AZ' },
  { start: 870, end: 884, state: 'NM' },
  { start: 885, end: 885, state: 'TX' },
  { start: 889, end: 898, state: 'NV' },
  { start: 900, end: 966, state: 'CA' },
  { start: 967, end: 968, state: 'HI' },
  { start: 970, end: 979, state: 'OR' },
  { start: 980, end: 994, state: 'WA' },
  { start: 995, end: 999, state: 'AK' },
];

// ---------------------------------------------------------------------------
// Reference points: ~826 locations across all 50 states + DC, each queried
// directly against the official USDA 2023 Plant Hardiness Zone boundary
// polygons (the same ARS/PRISM-sourced data behind planthardiness.ars.usda.gov,
// hosted as a public ArcGIS feature layer) via a point-in-polygon lookup at
// data-build time. Density is weighted toward mountainous and elevation-variable
// regions (Colorado, California, the Appalachians, the Pacific Northwest, the
// Mountain West generally) where zones can shift over short distances, and
// lighter in flat, climatically uniform regions where wide spacing is adequate.
// Alaska and Hawaii fall outside that layer's 48-state coverage and keep a
// single hand-verified reference point each, as in the original dataset.
//
// The ZIP entered is matched to the closest reference point *within its state*
// by ZIP3 numeric distance — a rough but real proxy for geographic proximity,
// not a precise address-level lookup. Accuracy is roughly within a half-zone
// across most of the country; in mountainous terrain, elevation can shift the
// true zone over a much shorter distance than this method can resolve. This
// whole ZIP path is a convenience estimate; the Hardiness Zone dropdown on the
// calculator is the exact input.
// ---------------------------------------------------------------------------
export interface RefCity {
  city: string;
  state: string;
  zip3: number;
  zone: string;
}

export const REFERENCE_CITIES: RefCity[] = [
  // AL
  { city: 'Birmingham, AL', state: 'AL', zip3: 352, zone: '8a' },
  { city: 'Tuscaloosa, AL', state: 'AL', zip3: 354, zone: '8b' },
  { city: 'Florence, AL', state: 'AL', zip3: 356, zone: '8a' },
  { city: 'Huntsville, AL', state: 'AL', zip3: 358, zone: '8a' },
  { city: 'Gadsden, AL', state: 'AL', zip3: 359, zone: '8a' },
  { city: 'Fort Payne (mountains), AL', state: 'AL', zip3: 359, zone: '8a' },
  { city: 'Montgomery, AL', state: 'AL', zip3: 361, zone: '8b' },
  { city: 'Anniston, AL', state: 'AL', zip3: 362, zone: '8a' },
  { city: 'Dothan, AL', state: 'AL', zip3: 363, zone: '9a' },
  { city: 'Gulf Shores, AL', state: 'AL', zip3: 365, zone: '9a' },
  { city: 'Mobile, AL', state: 'AL', zip3: 366, zone: '9a' },
  // AR
  { city: 'Pine Bluff, AR', state: 'AR', zip3: 716, zone: '8b' },
  { city: 'El Dorado, AR', state: 'AR', zip3: 717, zone: '8b' },
  { city: 'Texarkana, AR', state: 'AR', zip3: 718, zone: '8b' },
  { city: 'Hot Springs, AR', state: 'AR', zip3: 719, zone: '8a' },
  { city: 'Mena, AR', state: 'AR', zip3: 719, zone: '8a' },
  { city: 'Little Rock, AR', state: 'AR', zip3: 722, zone: '8a' },
  { city: 'Jonesboro, AR', state: 'AR', zip3: 724, zone: '7b' },
  { city: 'Mountain Home, AR', state: 'AR', zip3: 726, zone: '7b' },
  { city: 'Harrison, AR', state: 'AR', zip3: 726, zone: '7a' },
  { city: 'Fayetteville, AR', state: 'AR', zip3: 727, zone: '7a' },
  { city: 'Eureka Springs, AR', state: 'AR', zip3: 727, zone: '7a' },
  { city: 'Fort Smith, AR', state: 'AR', zip3: 729, zone: '8a' },
  // AZ
  { city: 'Phoenix, AZ', state: 'AZ', zip3: 850, zone: '10a' },
  { city: 'Casa Grande, AZ', state: 'AZ', zip3: 851, zone: '9a' },
  { city: 'Mesa, AZ', state: 'AZ', zip3: 852, zone: '10a' },
  { city: 'Scottsdale, AZ', state: 'AZ', zip3: 852, zone: '9b' },
  { city: 'Chandler, AZ', state: 'AZ', zip3: 852, zone: '9b' },
  { city: 'Yuma, AZ', state: 'AZ', zip3: 853, zone: '10a' },
  { city: 'Wickenburg, AZ', state: 'AZ', zip3: 853, zone: '9a' },
  { city: 'Payson, AZ', state: 'AZ', zip3: 855, zone: '8a' },
  { city: 'Safford, AZ', state: 'AZ', zip3: 855, zone: '8b' },
  { city: 'Globe, AZ', state: 'AZ', zip3: 855, zone: '9a' },
  { city: 'Nogales, AZ', state: 'AZ', zip3: 856, zone: '8b' },
  { city: 'Sierra Vista, AZ', state: 'AZ', zip3: 856, zone: '8b' },
  { city: 'Bisbee, AZ', state: 'AZ', zip3: 856, zone: '8b' },
  { city: 'Ajo, AZ', state: 'AZ', zip3: 856, zone: '10a' },
  { city: 'Tucson, AZ', state: 'AZ', zip3: 857, zone: '9b' },
  { city: 'Show Low, AZ', state: 'AZ', zip3: 859, zone: '7a' },
  { city: 'Pinetop-Lakeside, AZ', state: 'AZ', zip3: 859, zone: '6b' },
  { city: 'Flagstaff, AZ', state: 'AZ', zip3: 860, zone: '6a' },
  { city: 'Flagstaff-N (Grand Canyon), AZ', state: 'AZ', zip3: 860, zone: '7a' },
  { city: 'Williams, AZ', state: 'AZ', zip3: 860, zone: '7a' },
  { city: 'Winslow, AZ', state: 'AZ', zip3: 860, zone: '7a' },
  { city: 'Holbrook, AZ', state: 'AZ', zip3: 860, zone: '7a' },
  { city: 'Page, AZ', state: 'AZ', zip3: 860, zone: '8b' },
  { city: 'Sedona, AZ', state: 'AZ', zip3: 863, zone: '8b' },
  { city: 'Prescott, AZ', state: 'AZ', zip3: 863, zone: '7b' },
  { city: 'Prescott Valley, AZ', state: 'AZ', zip3: 863, zone: '7b' },
  { city: 'Kingman, AZ', state: 'AZ', zip3: 864, zone: '8b' },
  { city: 'Bullhead City, AZ', state: 'AZ', zip3: 864, zone: '10a' },
  { city: 'Lake Havasu City, AZ', state: 'AZ', zip3: 864, zone: '10a' },
  { city: 'Chinle, AZ', state: 'AZ', zip3: 865, zone: '7a' },
  // CA
  { city: 'Los Angeles, CA', state: 'CA', zip3: 900, zone: '10b' },
  { city: 'Santa Monica, CA', state: 'CA', zip3: 904, zone: '11a' },
  { city: 'Long Beach, CA', state: 'CA', zip3: 908, zone: '10b' },
  { city: 'Pasadena, CA', state: 'CA', zip3: 911, zone: '10b' },
  { city: 'Julian, CA', state: 'CA', zip3: 920, zone: '9a' },
  { city: 'Escondido, CA', state: 'CA', zip3: 920, zone: '10a' },
  { city: 'San Diego, CA', state: 'CA', zip3: 921, zone: '10b' },
  { city: 'Palm Springs, CA', state: 'CA', zip3: 922, zone: '10a' },
  { city: 'El Centro, CA', state: 'CA', zip3: 922, zone: '10a' },
  { city: 'Twentynine Palms, CA', state: 'CA', zip3: 922, zone: '9a' },
  { city: 'Blythe, CA', state: 'CA', zip3: 922, zone: '9b' },
  { city: 'Big Bear Lake, CA', state: 'CA', zip3: 923, zone: '7a' },
  { city: 'Death Valley, CA', state: 'CA', zip3: 923, zone: '9b' },
  { city: 'Barstow, CA', state: 'CA', zip3: 923, zone: '9a' },
  { city: 'San Bernardino, CA', state: 'CA', zip3: 924, zone: '10a' },
  { city: 'Riverside, CA', state: 'CA', zip3: 925, zone: '10a' },
  { city: 'Idyllwild, CA', state: 'CA', zip3: 925, zone: '8b' },
  { city: 'Temecula, CA', state: 'CA', zip3: 925, zone: '9b' },
  { city: 'Orange, CA', state: 'CA', zip3: 926, zone: '10b' },
  { city: 'Irvine, CA', state: 'CA', zip3: 926, zone: '10b' },
  { city: 'Anaheim, CA', state: 'CA', zip3: 928, zone: '10b' },
  { city: 'Ventura, CA', state: 'CA', zip3: 930, zone: '10b' },
  { city: 'Oxnard, CA', state: 'CA', zip3: 930, zone: '10b' },
  { city: 'Santa Barbara, CA', state: 'CA', zip3: 931, zone: '10b' },
  { city: 'Visalia, CA', state: 'CA', zip3: 932, zone: '9b' },
  { city: 'Bakersfield, CA', state: 'CA', zip3: 933, zone: '9b' },
  { city: 'San Luis Obispo, CA', state: 'CA', zip3: 934, zone: '10a' },
  { city: 'Santa Maria, CA', state: 'CA', zip3: 934, zone: '9b' },
  { city: 'Lompoc, CA', state: 'CA', zip3: 934, zone: '10a' },
  { city: 'Palmdale, CA', state: 'CA', zip3: 935, zone: '9a' },
  { city: 'Lancaster, CA', state: 'CA', zip3: 935, zone: '8b' },
  { city: 'Tehachapi, CA', state: 'CA', zip3: 935, zone: '8b' },
  { city: 'Ridgecrest, CA', state: 'CA', zip3: 935, zone: '8b' },
  { city: 'Mammoth Lakes, CA', state: 'CA', zip3: 935, zone: '6a' },
  { city: 'Bishop, CA', state: 'CA', zip3: 935, zone: '8a' },
  { city: 'Bridgeport, CA', state: 'CA', zip3: 935, zone: '6a' },
  { city: 'Lone Pine, CA', state: 'CA', zip3: 935, zone: '8a' },
  { city: 'Fresno, CA', state: 'CA', zip3: 936, zone: '9b' },
  { city: 'Salinas, CA', state: 'CA', zip3: 939, zone: '9b' },
  { city: 'Monterey, CA', state: 'CA', zip3: 939, zone: '10a' },
  { city: 'San Francisco, CA', state: 'CA', zip3: 941, zone: '10b' },
  { city: 'Napa, CA', state: 'CA', zip3: 945, zone: '9b' },
  { city: 'Oakland, CA', state: 'CA', zip3: 946, zone: '10a' },
  { city: 'Berkeley, CA', state: 'CA', zip3: 947, zone: '10a' },
  { city: 'Santa Cruz, CA', state: 'CA', zip3: 950, zone: '10a' },
  { city: 'San Jose, CA', state: 'CA', zip3: 951, zone: '9b' },
  { city: 'Stockton, CA', state: 'CA', zip3: 952, zone: '9b' },
  { city: 'Modesto, CA', state: 'CA', zip3: 953, zone: '9b' },
  { city: 'Sonora, CA', state: 'CA', zip3: 953, zone: '9a' },
  { city: 'Mariposa, CA', state: 'CA', zip3: 953, zone: '9a' },
  { city: 'Yosemite Valley, CA', state: 'CA', zip3: 953, zone: '8a' },
  { city: 'Santa Rosa, CA', state: 'CA', zip3: 954, zone: '9b' },
  { city: 'Ukiah, CA', state: 'CA', zip3: 954, zone: '9a' },
  { city: 'Willits, CA', state: 'CA', zip3: 954, zone: '8b' },
  { city: 'Eureka, CA', state: 'CA', zip3: 955, zone: '9b' },
  { city: 'Crescent City, CA', state: 'CA', zip3: 955, zone: '9b' },
  { city: 'Placerville, CA', state: 'CA', zip3: 956, zone: '9b' },
  { city: 'Auburn, CA', state: 'CA', zip3: 956, zone: '9b' },
  { city: 'Sacramento, CA', state: 'CA', zip3: 958, zone: '9b' },
  { city: 'Chico, CA', state: 'CA', zip3: 959, zone: '9a' },
  { city: 'Marysville, CA', state: 'CA', zip3: 959, zone: '9b' },
  { city: 'Quincy, CA', state: 'CA', zip3: 959, zone: '7b' },
  { city: 'Redding, CA', state: 'CA', zip3: 960, zone: '9b' },
  { city: 'Mount Shasta, CA', state: 'CA', zip3: 960, zone: '7b' },
  { city: 'Yreka, CA', state: 'CA', zip3: 960, zone: '8a' },
  { city: 'Weaverville, CA', state: 'CA', zip3: 960, zone: '8b' },
  { city: 'South Lake Tahoe, CA', state: 'CA', zip3: 961, zone: '6b' },
  { city: 'Truckee, CA', state: 'CA', zip3: 961, zone: '6a' },
  { city: 'Alturas, CA', state: 'CA', zip3: 961, zone: '6a' },
  { city: 'Susanville, CA', state: 'CA', zip3: 961, zone: '7a' },
  { city: 'Portola, CA', state: 'CA', zip3: 961, zone: '6b' },
  // CO
  { city: 'Aurora, CO', state: 'CO', zip3: 800, zone: '6a' },
  { city: 'Denver, CO', state: 'CO', zip3: 802, zone: '6a' },
  { city: 'Boulder, CO', state: 'CO', zip3: 803, zone: '6a' },
  { city: 'Steamboat Springs, CO', state: 'CO', zip3: 804, zone: '4b' },
  { city: 'Breckenridge, CO', state: 'CO', zip3: 804, zone: '5a' },
  { city: 'Leadville, CO', state: 'CO', zip3: 804, zone: '5a' },
  { city: 'Golden, CO', state: 'CO', zip3: 804, zone: '6a' },
  { city: 'Evergreen, CO', state: 'CO', zip3: 804, zone: '5b' },
  { city: 'Winter Park, CO', state: 'CO', zip3: 804, zone: '5a' },
  { city: 'Granby, CO', state: 'CO', zip3: 804, zone: '4a' },
  { city: 'Fort Collins, CO', state: 'CO', zip3: 805, zone: '5b' },
  { city: 'Estes Park, CO', state: 'CO', zip3: 805, zone: '5b' },
  { city: 'Longmont, CO', state: 'CO', zip3: 805, zone: '5b' },
  { city: 'Loveland, CO', state: 'CO', zip3: 805, zone: '5b' },
  { city: 'Greeley, CO', state: 'CO', zip3: 806, zone: '5b' },
  { city: 'Sterling, CO', state: 'CO', zip3: 807, zone: '5b' },
  { city: 'Fort Morgan, CO', state: 'CO', zip3: 807, zone: '5b' },
  { city: 'Julesburg, CO', state: 'CO', zip3: 807, zone: '5b' },
  { city: 'Yuma, CO', state: 'CO', zip3: 807, zone: '5b' },
  { city: 'Woodland Park, CO', state: 'CO', zip3: 808, zone: '5a' },
  { city: 'Limon, CO', state: 'CO', zip3: 808, zone: '5b' },
  { city: 'Burlington, CO', state: 'CO', zip3: 808, zone: '6a' },
  { city: 'Cheyenne Wells, CO', state: 'CO', zip3: 808, zone: '6a' },
  { city: 'Colorado Springs, CO', state: 'CO', zip3: 809, zone: '6a' },
  { city: 'Pueblo, CO', state: 'CO', zip3: 810, zone: '6a' },
  { city: 'Trinidad, CO', state: 'CO', zip3: 810, zone: '6a' },
  { city: 'La Junta, CO', state: 'CO', zip3: 810, zone: '6a' },
  { city: 'Lamar, CO', state: 'CO', zip3: 810, zone: '6a' },
  { city: 'Walsenburg, CO', state: 'CO', zip3: 810, zone: '6a' },
  { city: 'Alamosa, CO', state: 'CO', zip3: 811, zone: '4b' },
  { city: 'Del Norte, CO', state: 'CO', zip3: 811, zone: '5b' },
  { city: 'Pagosa Springs, CO', state: 'CO', zip3: 811, zone: '5b' },
  { city: 'Gunnison, CO', state: 'CO', zip3: 812, zone: '4a' },
  { city: 'Salida, CO', state: 'CO', zip3: 812, zone: '5b' },
  { city: 'Buena Vista, CO', state: 'CO', zip3: 812, zone: '5b' },
  { city: 'Canon City, CO', state: 'CO', zip3: 812, zone: '6a' },
  { city: 'Durango, CO', state: 'CO', zip3: 813, zone: '6b' },
  { city: 'Telluride, CO', state: 'CO', zip3: 814, zone: '5b' },
  { city: 'Montrose, CO', state: 'CO', zip3: 814, zone: '6b' },
  { city: 'Silverton, CO', state: 'CO', zip3: 814, zone: '4b' },
  { city: 'Ouray, CO', state: 'CO', zip3: 814, zone: '6a' },
  { city: 'Delta, CO', state: 'CO', zip3: 814, zone: '6b' },
  { city: 'Grand Junction, CO', state: 'CO', zip3: 815, zone: '7a' },
  { city: 'Cortez, CO', state: 'CO', zip3: 815, zone: '6a' },
  { city: 'Vail, CO', state: 'CO', zip3: 816, zone: '5a' },
  { city: 'Aspen, CO', state: 'CO', zip3: 816, zone: '5b' },
  { city: 'Glenwood Springs, CO', state: 'CO', zip3: 816, zone: '6a' },
  { city: 'Craig, CO', state: 'CO', zip3: 816, zone: '4a' },
  { city: 'Rifle, CO', state: 'CO', zip3: 816, zone: '6a' },
  { city: 'Rangely, CO', state: 'CO', zip3: 816, zone: '5a' },
  { city: 'Meeker, CO', state: 'CO', zip3: 816, zone: '4b' },
  // CT
  { city: 'Hartford, CT', state: 'CT', zip3: 61, zone: '6b' },
  { city: 'Norwich, CT', state: 'CT', zip3: 63, zone: '6b' },
  { city: 'New Haven, CT', state: 'CT', zip3: 65, zone: '7a' },
  { city: 'Bridgeport, CT', state: 'CT', zip3: 66, zone: '7a' },
  { city: 'Litchfield, CT', state: 'CT', zip3: 67, zone: '6a' },
  { city: 'Stamford, CT', state: 'CT', zip3: 69, zone: '7a' },
  // DC
  { city: 'Washington, DC', state: 'DC', zip3: 200, zone: '8a' },
  // DE
  { city: 'Wilmington, DE', state: 'DE', zip3: 198, zone: '7b' },
  { city: 'Dover, DE', state: 'DE', zip3: 199, zone: '7b' },
  { city: 'Georgetown, DE', state: 'DE', zip3: 199, zone: '7b' },
  { city: 'Rehoboth Beach, DE', state: 'DE', zip3: 199, zone: '8a' },
  // FL
  { city: 'Daytona Beach, FL', state: 'FL', zip3: 321, zone: '10a' },
  { city: 'Jacksonville, FL', state: 'FL', zip3: 322, zone: '9b' },
  { city: 'Tallahassee, FL', state: 'FL', zip3: 323, zone: '9a' },
  { city: 'Panama City, FL', state: 'FL', zip3: 324, zone: '9b' },
  { city: 'Pensacola, FL', state: 'FL', zip3: 325, zone: '9a' },
  { city: 'Gainesville, FL', state: 'FL', zip3: 326, zone: '9a' },
  { city: 'Orlando, FL', state: 'FL', zip3: 328, zone: '10a' },
  { city: 'Key West, FL', state: 'FL', zip3: 330, zone: '11b' },
  { city: 'Miami, FL', state: 'FL', zip3: 331, zone: '11a' },
  { city: 'Fort Lauderdale, FL', state: 'FL', zip3: 333, zone: '11a' },
  { city: 'Tampa, FL', state: 'FL', zip3: 336, zone: '10a' },
  { city: 'Fort Myers, FL', state: 'FL', zip3: 339, zone: '10b' },
  { city: 'Naples, FL', state: 'FL', zip3: 341, zone: '10b' },
  { city: 'Sarasota, FL', state: 'FL', zip3: 342, zone: '10a' },
  { city: 'Ocala, FL', state: 'FL', zip3: 344, zone: '9a' },
  // GA
  { city: 'Rome, GA', state: 'GA', zip3: 301, zone: '8a' },
  { city: 'Atlanta, GA', state: 'GA', zip3: 303, zone: '8a' },
  { city: 'Blairsville, GA', state: 'GA', zip3: 305, zone: '7a' },
  { city: 'Blue Ridge, GA', state: 'GA', zip3: 305, zone: '7b' },
  { city: 'Dahlonega, GA', state: 'GA', zip3: 305, zone: '8a' },
  { city: 'Helen, GA', state: 'GA', zip3: 305, zone: '8a' },
  { city: 'Clayton, GA', state: 'GA', zip3: 305, zone: '7b' },
  { city: 'Gainesville, GA', state: 'GA', zip3: 305, zone: '8a' },
  { city: 'Athens, GA', state: 'GA', zip3: 306, zone: '8b' },
  { city: 'Dalton, GA', state: 'GA', zip3: 307, zone: '8a' },
  { city: 'Augusta, GA', state: 'GA', zip3: 309, zone: '8b' },
  { city: 'Macon, GA', state: 'GA', zip3: 312, zone: '8b' },
  { city: 'Savannah, GA', state: 'GA', zip3: 314, zone: '9a' },
  { city: 'Brunswick, GA', state: 'GA', zip3: 315, zone: '9a' },
  { city: 'Waycross, GA', state: 'GA', zip3: 315, zone: '9a' },
  { city: 'Valdosta, GA', state: 'GA', zip3: 316, zone: '9a' },
  { city: 'Albany, GA', state: 'GA', zip3: 317, zone: '9a' },
  { city: 'Columbus, GA', state: 'GA', zip3: 319, zone: '8b' },
  // IA
  { city: 'Des Moines, IA', state: 'IA', zip3: 503, zone: '5b' },
  { city: 'Waterloo, IA', state: 'IA', zip3: 507, zone: '5a' },
  { city: 'Sioux City, IA', state: 'IA', zip3: 511, zone: '5a' },
  { city: 'Council Bluffs, IA', state: 'IA', zip3: 515, zone: '5b' },
  { city: 'Dubuque, IA', state: 'IA', zip3: 520, zone: '5a' },
  { city: 'Cedar Rapids, IA', state: 'IA', zip3: 524, zone: '5b' },
  { city: 'Ottumwa, IA', state: 'IA', zip3: 525, zone: '5b' },
  { city: 'Davenport, IA', state: 'IA', zip3: 528, zone: '5b' },
  // ID
  { city: 'Pocatello, ID', state: 'ID', zip3: 832, zone: '6a' },
  { city: 'Challis, ID', state: 'ID', zip3: 832, zone: '5b' },
  { city: 'Soda Springs, ID', state: 'ID', zip3: 832, zone: '5a' },
  { city: 'Blackfoot, ID', state: 'ID', zip3: 832, zone: '5b' },
  { city: 'Twin Falls, ID', state: 'ID', zip3: 833, zone: '6b' },
  { city: 'Stanley, ID', state: 'ID', zip3: 833, zone: '4a' },
  { city: 'Sun Valley, ID', state: 'ID', zip3: 833, zone: '5b' },
  { city: 'Burley, ID', state: 'ID', zip3: 833, zone: '6b' },
  { city: 'Idaho Falls, ID', state: 'ID', zip3: 834, zone: '5b' },
  { city: 'Salmon, ID', state: 'ID', zip3: 834, zone: '5b' },
  { city: 'Rexburg, ID', state: 'ID', zip3: 834, zone: '5a' },
  { city: 'Driggs, ID', state: 'ID', zip3: 834, zone: '5a' },
  { city: 'Ashton, ID', state: 'ID', zip3: 834, zone: '5a' },
  { city: 'Lewiston, ID', state: 'ID', zip3: 835, zone: '7b' },
  { city: 'Grangeville, ID', state: 'ID', zip3: 835, zone: '6b' },
  { city: 'Orofino, ID', state: 'ID', zip3: 835, zone: '7b' },
  { city: 'Meridian, ID', state: 'ID', zip3: 836, zone: '7a' },
  { city: 'Nampa, ID', state: 'ID', zip3: 836, zone: '7a' },
  { city: 'McCall, ID', state: 'ID', zip3: 836, zone: '5a' },
  { city: 'Weiser, ID', state: 'ID', zip3: 836, zone: '7a' },
  { city: 'Boise, ID', state: 'ID', zip3: 837, zone: '7a' },
  { city: 'Coeur d’Alene, ID', state: 'ID', zip3: 838, zone: '7a' },
  { city: 'Sandpoint, ID', state: 'ID', zip3: 838, zone: '6b' },
  { city: 'Moscow, ID', state: 'ID', zip3: 838, zone: '6b' },
  { city: 'Bonners Ferry, ID', state: 'ID', zip3: 838, zone: '6b' },
  // IL
  { city: 'Aurora, IL', state: 'IL', zip3: 605, zone: '5b' },
  { city: 'Chicago, IL', state: 'IL', zip3: 606, zone: '6b' },
  { city: 'Galena (NW hills), IL', state: 'IL', zip3: 610, zone: '5a' },
  { city: 'Rockford, IL', state: 'IL', zip3: 611, zone: '5b' },
  { city: 'Rock Island, IL', state: 'IL', zip3: 612, zone: '5b' },
  { city: 'Peoria, IL', state: 'IL', zip3: 616, zone: '6a' },
  { city: 'Champaign, IL', state: 'IL', zip3: 618, zone: '6a' },
  { city: 'Quincy, IL', state: 'IL', zip3: 623, zone: '6a' },
  { city: 'Springfield, IL', state: 'IL', zip3: 627, zone: '6a' },
  { city: 'Carbondale, IL', state: 'IL', zip3: 629, zone: '7a' },
  // IN
  { city: 'Indianapolis, IN', state: 'IN', zip3: 462, zone: '6b' },
  { city: 'South Bend, IN', state: 'IN', zip3: 466, zone: '6a' },
  { city: 'Fort Wayne, IN', state: 'IN', zip3: 468, zone: '6a' },
  { city: 'Muncie, IN', state: 'IN', zip3: 473, zone: '6a' },
  { city: 'Bloomington, IN', state: 'IN', zip3: 474, zone: '6b' },
  { city: 'Evansville, IN', state: 'IN', zip3: 477, zone: '7a' },
  { city: 'Terre Haute, IN', state: 'IN', zip3: 478, zone: '6a' },
  { city: 'Lafayette, IN', state: 'IN', zip3: 479, zone: '6a' },
  // KS
  { city: 'Overland Park, KS', state: 'KS', zip3: 662, zone: '6b' },
  { city: 'Topeka, KS', state: 'KS', zip3: 666, zone: '6b' },
  { city: 'Pittsburg, KS', state: 'KS', zip3: 667, zone: '7a' },
  { city: 'Wichita, KS', state: 'KS', zip3: 672, zone: '7a' },
  { city: 'Salina, KS', state: 'KS', zip3: 674, zone: '6b' },
  { city: 'Hays, KS', state: 'KS', zip3: 676, zone: '6b' },
  { city: 'Goodland, KS', state: 'KS', zip3: 677, zone: '6a' },
  { city: 'Garden City, KS', state: 'KS', zip3: 678, zone: '6b' },
  { city: 'Dodge City, KS', state: 'KS', zip3: 678, zone: '6b' },
  // KY
  { city: 'Louisville, KY', state: 'KY', zip3: 402, zone: '7a' },
  { city: 'Berea, KY', state: 'KY', zip3: 404, zone: '7a' },
  { city: 'Lexington, KY', state: 'KY', zip3: 405, zone: '7a' },
  { city: 'Corbin, KY', state: 'KY', zip3: 407, zone: '7a' },
  { city: 'Covington, KY', state: 'KY', zip3: 410, zone: '6b' },
  { city: 'Ashland, KY', state: 'KY', zip3: 411, zone: '7a' },
  { city: 'Pikeville, KY', state: 'KY', zip3: 415, zone: '7a' },
  { city: 'Hazard, KY', state: 'KY', zip3: 417, zone: '7a' },
  { city: 'Paducah, KY', state: 'KY', zip3: 420, zone: '7a' },
  { city: 'Bowling Green, KY', state: 'KY', zip3: 421, zone: '7a' },
  { city: 'Owensboro, KY', state: 'KY', zip3: 423, zone: '7a' },
  { city: 'Somerset, KY', state: 'KY', zip3: 425, zone: '7a' },
  // LA
  { city: 'New Orleans, LA', state: 'LA', zip3: 701, zone: '9b' },
  { city: 'Houma, LA', state: 'LA', zip3: 703, zone: '9b' },
  { city: 'Lafayette, LA', state: 'LA', zip3: 705, zone: '9a' },
  { city: 'Lake Charles, LA', state: 'LA', zip3: 706, zone: '9a' },
  { city: 'Baton Rouge, LA', state: 'LA', zip3: 708, zone: '9a' },
  { city: 'Shreveport, LA', state: 'LA', zip3: 711, zone: '8b' },
  { city: 'Monroe, LA', state: 'LA', zip3: 712, zone: '8b' },
  { city: 'Alexandria, LA', state: 'LA', zip3: 713, zone: '9a' },
  // MA
  { city: 'Springfield, MA', state: 'MA', zip3: 11, zone: '6b' },
  { city: 'Pittsfield (Berkshires), MA', state: 'MA', zip3: 12, zone: '5b' },
  { city: 'Worcester, MA', state: 'MA', zip3: 16, zone: '6a' },
  { city: 'Lowell, MA', state: 'MA', zip3: 18, zone: '6b' },
  { city: 'Boston, MA', state: 'MA', zip3: 21, zone: '7a' },
  { city: 'Nantucket, MA', state: 'MA', zip3: 25, zone: '7b' },
  { city: 'Cape Cod (Hyannis), MA', state: 'MA', zip3: 26, zone: '7a' },
  { city: 'New Bedford, MA', state: 'MA', zip3: 27, zone: '7a' },
  // MD
  { city: 'Rockville, MD', state: 'MD', zip3: 208, zone: '7b' },
  { city: 'Baltimore, MD', state: 'MD', zip3: 212, zone: '8a' },
  { city: 'Annapolis, MD', state: 'MD', zip3: 214, zone: '8a' },
  { city: 'Cumberland, MD', state: 'MD', zip3: 215, zone: '7a' },
  { city: 'Frederick, MD', state: 'MD', zip3: 217, zone: '7b' },
  { city: 'Hagerstown, MD', state: 'MD', zip3: 217, zone: '7a' },
  { city: 'Salisbury, MD', state: 'MD', zip3: 218, zone: '7b' },
  { city: 'Ocean City, MD', state: 'MD', zip3: 218, zone: '8a' },
  // ME
  { city: 'Portland, ME', state: 'ME', zip3: 41, zone: '6a' },
  { city: 'Lewiston, ME', state: 'ME', zip3: 42, zone: '5b' },
  { city: 'Rumford, ME', state: 'ME', zip3: 42, zone: '5a' },
  { city: 'Bethel, ME', state: 'ME', zip3: 42, zone: '5a' },
  { city: 'Augusta, ME', state: 'ME', zip3: 43, zone: '5b' },
  { city: 'Bangor, ME', state: 'ME', zip3: 44, zone: '5a' },
  { city: 'Greenville, ME', state: 'ME', zip3: 44, zone: '5a' },
  { city: 'Bar Harbor, ME', state: 'ME', zip3: 46, zone: '6a' },
  { city: 'Machias, ME', state: 'ME', zip3: 46, zone: '5b' },
  { city: 'Presque Isle, ME', state: 'ME', zip3: 47, zone: '4a' },
  { city: 'Caribou, ME', state: 'ME', zip3: 47, zone: '4a' },
  { city: 'Fort Kent, ME', state: 'ME', zip3: 47, zone: '4a' },
  { city: 'Rangeley, ME', state: 'ME', zip3: 49, zone: '4b' },
  { city: 'Sugarloaf (Carrabassett), ME', state: 'ME', zip3: 49, zone: '4b' },
  { city: 'Farmington, ME', state: 'ME', zip3: 49, zone: '5a' },
  // MI
  { city: 'Ann Arbor, MI', state: 'MI', zip3: 481, zone: '6a' },
  { city: 'Detroit, MI', state: 'MI', zip3: 482, zone: '6b' },
  { city: 'Flint, MI', state: 'MI', zip3: 485, zone: '6a' },
  { city: 'Saginaw, MI', state: 'MI', zip3: 486, zone: '6a' },
  { city: 'Lansing, MI', state: 'MI', zip3: 489, zone: '6a' },
  { city: 'Kalamazoo, MI', state: 'MI', zip3: 490, zone: '6a' },
  { city: 'Muskegon, MI', state: 'MI', zip3: 494, zone: '6b' },
  { city: 'Grand Rapids, MI', state: 'MI', zip3: 495, zone: '6a' },
  { city: 'Traverse City, MI', state: 'MI', zip3: 496, zone: '6b' },
  { city: 'Sault Ste. Marie, MI', state: 'MI', zip3: 497, zone: '5a' },
  { city: 'Gaylord, MI', state: 'MI', zip3: 497, zone: '5a' },
  { city: 'Alpena, MI', state: 'MI', zip3: 497, zone: '6a' },
  { city: 'Petoskey, MI', state: 'MI', zip3: 497, zone: '5b' },
  { city: 'Marquette, MI', state: 'MI', zip3: 498, zone: '5b' },
  { city: 'Escanaba, MI', state: 'MI', zip3: 498, zone: '5a' },
  { city: 'Iron Mountain, MI', state: 'MI', zip3: 498, zone: '4b' },
  { city: 'Houghton, MI', state: 'MI', zip3: 499, zone: '5b' },
  { city: 'Ironwood, MI', state: 'MI', zip3: 499, zone: '4b' },
  // MN
  { city: 'Saint Paul, MN', state: 'MN', zip3: 551, zone: '5a' },
  { city: 'Minneapolis, MN', state: 'MN', zip3: 554, zone: '5a' },
  { city: 'Grand Marais, MN', state: 'MN', zip3: 556, zone: '5a' },
  { city: 'Ely, MN', state: 'MN', zip3: 557, zone: '3b' },
  { city: 'Duluth, MN', state: 'MN', zip3: 558, zone: '4b' },
  { city: 'Rochester, MN', state: 'MN', zip3: 559, zone: '4b' },
  { city: 'Mankato, MN', state: 'MN', zip3: 560, zone: '5a' },
  { city: 'Marshall, MN', state: 'MN', zip3: 562, zone: '5a' },
  { city: 'Alexandria, MN', state: 'MN', zip3: 563, zone: '4b' },
  { city: 'St. Cloud, MN', state: 'MN', zip3: 563, zone: '4b' },
  { city: 'Brainerd, MN', state: 'MN', zip3: 564, zone: '4a' },
  { city: 'Moorhead, MN', state: 'MN', zip3: 565, zone: '4a' },
  { city: 'International Falls, MN', state: 'MN', zip3: 566, zone: '3b' },
  { city: 'Bemidji, MN', state: 'MN', zip3: 566, zone: '3b' },
  // MO
  { city: 'St. Louis, MO', state: 'MO', zip3: 631, zone: '7a' },
  { city: 'Hannibal, MO', state: 'MO', zip3: 634, zone: '6b' },
  { city: 'Cape Girardeau, MO', state: 'MO', zip3: 637, zone: '7a' },
  { city: 'Kansas City, MO', state: 'MO', zip3: 641, zone: '6b' },
  { city: 'St. Joseph, MO', state: 'MO', zip3: 645, zone: '6a' },
  { city: 'Joplin, MO', state: 'MO', zip3: 648, zone: '7a' },
  { city: 'Columbia, MO', state: 'MO', zip3: 652, zone: '6b' },
  { city: 'Rolla, MO', state: 'MO', zip3: 654, zone: '6b' },
  { city: 'Branson (Ozarks), MO', state: 'MO', zip3: 657, zone: '7a' },
  { city: 'Springfield, MO', state: 'MO', zip3: 658, zone: '6b' },
  // MS
  { city: 'Oxford, MS', state: 'MS', zip3: 386, zone: '7b' },
  { city: 'Greenville, MS', state: 'MS', zip3: 387, zone: '8b' },
  { city: 'Tupelo, MS', state: 'MS', zip3: 388, zone: '8a' },
  { city: 'Natchez, MS', state: 'MS', zip3: 391, zone: '8b' },
  { city: 'Jackson, MS', state: 'MS', zip3: 392, zone: '8b' },
  { city: 'Meridian, MS', state: 'MS', zip3: 393, zone: '8b' },
  { city: 'Hattiesburg, MS', state: 'MS', zip3: 394, zone: '8b' },
  { city: 'Gulfport, MS', state: 'MS', zip3: 395, zone: '9a' },
  { city: 'Biloxi, MS', state: 'MS', zip3: 395, zone: '9a' },
  { city: 'Columbus, MS', state: 'MS', zip3: 397, zone: '8b' },
  // MT
  { city: 'Livingston, MT', state: 'MT', zip3: 590, zone: '5a' },
  { city: 'Red Lodge, MT', state: 'MT', zip3: 590, zone: '5a' },
  { city: 'Billings, MT', state: 'MT', zip3: 591, zone: '5a' },
  { city: 'Glasgow, MT', state: 'MT', zip3: 592, zone: '4a' },
  { city: 'Wolf Point, MT', state: 'MT', zip3: 592, zone: '4a' },
  { city: 'Cody-area (Ekalaka), MT', state: 'MT', zip3: 593, zone: '4b' },
  { city: 'Miles City, MT', state: 'MT', zip3: 593, zone: '4a' },
  { city: 'Glendive, MT', state: 'MT', zip3: 593, zone: '4a' },
  { city: 'Sidney, MT', state: 'MT', zip3: 593, zone: '4a' },
  { city: 'Great Falls, MT', state: 'MT', zip3: 594, zone: '4b' },
  { city: 'Lewistown, MT', state: 'MT', zip3: 594, zone: '4b' },
  { city: 'Cut Bank, MT', state: 'MT', zip3: 594, zone: '4a' },
  { city: 'Shelby, MT', state: 'MT', zip3: 594, zone: '4a' },
  { city: 'Havre, MT', state: 'MT', zip3: 595, zone: '4a' },
  { city: 'Helena, MT', state: 'MT', zip3: 596, zone: '5a' },
  { city: 'Bozeman, MT', state: 'MT', zip3: 597, zone: '5a' },
  { city: 'Butte, MT', state: 'MT', zip3: 597, zone: '4a' },
  { city: 'West Yellowstone, MT', state: 'MT', zip3: 597, zone: '3b' },
  { city: 'Dillon, MT', state: 'MT', zip3: 597, zone: '5a' },
  { city: 'Anaconda, MT', state: 'MT', zip3: 597, zone: '4b' },
  { city: 'Missoula, MT', state: 'MT', zip3: 598, zone: '6a' },
  { city: 'Kalispell, MT', state: 'MT', zip3: 599, zone: '5b' },
  { city: 'Whitefish, MT', state: 'MT', zip3: 599, zone: '5b' },
  { city: 'Libby, MT', state: 'MT', zip3: 599, zone: '6a' },
  { city: 'Bigfork (Flathead Lake), MT', state: 'MT', zip3: 599, zone: '5b' },
  // NC
  { city: 'Mount Airy, NC', state: 'NC', zip3: 270, zone: '7b' },
  { city: 'Winston-Salem, NC', state: 'NC', zip3: 271, zone: '8a' },
  { city: 'Greensboro, NC', state: 'NC', zip3: 274, zone: '8a' },
  { city: 'Raleigh, NC', state: 'NC', zip3: 276, zone: '8a' },
  { city: 'Durham, NC', state: 'NC', zip3: 277, zone: '8a' },
  { city: 'Greenville, NC', state: 'NC', zip3: 278, zone: '8a' },
  { city: 'Elizabeth City, NC', state: 'NC', zip3: 279, zone: '8a' },
  { city: 'Outer Banks (Manteo), NC', state: 'NC', zip3: 279, zone: '9a' },
  { city: 'Charlotte, NC', state: 'NC', zip3: 282, zone: '8a' },
  { city: 'Fayetteville, NC', state: 'NC', zip3: 283, zone: '8b' },
  { city: 'Wilmington, NC', state: 'NC', zip3: 284, zone: '8b' },
  { city: 'Boone, NC', state: 'NC', zip3: 286, zone: '7a' },
  { city: 'Blowing Rock, NC', state: 'NC', zip3: 286, zone: '6b' },
  { city: 'Wilkesboro, NC', state: 'NC', zip3: 286, zone: '7b' },
  { city: 'Spruce Pine, NC', state: 'NC', zip3: 286, zone: '7a' },
  { city: 'Banner Elk, NC', state: 'NC', zip3: 286, zone: '6b' },
  { city: 'Hickory, NC', state: 'NC', zip3: 286, zone: '8a' },
  { city: 'Morganton, NC', state: 'NC', zip3: 286, zone: '7b' },
  { city: 'Highlands, NC', state: 'NC', zip3: 287, zone: '7a' },
  { city: 'Cashiers, NC', state: 'NC', zip3: 287, zone: '7a' },
  { city: 'Waynesville, NC', state: 'NC', zip3: 287, zone: '7a' },
  { city: 'Bryson City, NC', state: 'NC', zip3: 287, zone: '7b' },
  { city: 'Hendersonville, NC', state: 'NC', zip3: 287, zone: '7b' },
  { city: 'Franklin, NC', state: 'NC', zip3: 287, zone: '7b' },
  { city: 'Asheville, NC', state: 'NC', zip3: 288, zone: '7b' },
  // ND
  { city: 'Fargo, ND', state: 'ND', zip3: 581, zone: '4a' },
  { city: 'Grand Forks, ND', state: 'ND', zip3: 582, zone: '4a' },
  { city: 'Bismarck, ND', state: 'ND', zip3: 585, zone: '4a' },
  { city: 'Dickinson, ND', state: 'ND', zip3: 586, zone: '4a' },
  { city: 'Minot, ND', state: 'ND', zip3: 587, zone: '4a' },
  { city: 'Williston, ND', state: 'ND', zip3: 588, zone: '4a' },
  // NE
  { city: 'Omaha, NE', state: 'NE', zip3: 681, zone: '6a' },
  { city: 'Lincoln, NE', state: 'NE', zip3: 685, zone: '6a' },
  { city: 'Norfolk, NE', state: 'NE', zip3: 687, zone: '5a' },
  { city: 'Grand Island, NE', state: 'NE', zip3: 688, zone: '5b' },
  { city: 'McCook, NE', state: 'NE', zip3: 690, zone: '6a' },
  { city: 'North Platte, NE', state: 'NE', zip3: 691, zone: '5b' },
  { city: 'Scottsbluff, NE', state: 'NE', zip3: 693, zone: '5a' },
  { city: 'Chadron, NE', state: 'NE', zip3: 693, zone: '5a' },
  // NH
  { city: 'Nashua, NH', state: 'NH', zip3: 30, zone: '6a' },
  { city: 'Manchester, NH', state: 'NH', zip3: 31, zone: '6a' },
  { city: 'Laconia, NH', state: 'NH', zip3: 32, zone: '6a' },
  { city: 'Concord, NH', state: 'NH', zip3: 33, zone: '5b' },
  { city: 'Keene, NH', state: 'NH', zip3: 34, zone: '5b' },
  { city: 'Berlin, NH', state: 'NH', zip3: 35, zone: '4b' },
  { city: 'Franconia, NH', state: 'NH', zip3: 35, zone: '5a' },
  { city: 'Lincoln, NH', state: 'NH', zip3: 35, zone: '5a' },
  { city: 'Littleton, NH', state: 'NH', zip3: 35, zone: '4b' },
  { city: 'Colebrook, NH', state: 'NH', zip3: 35, zone: '4a' },
  { city: 'Lebanon, NH', state: 'NH', zip3: 37, zone: '5a' },
  { city: 'North Conway, NH', state: 'NH', zip3: 38, zone: '5b' },
  // NJ
  { city: 'Newark, NJ', state: 'NJ', zip3: 71, zone: '7b' },
  { city: 'Jersey City, NJ', state: 'NJ', zip3: 73, zone: '7b' },
  { city: 'Sussex, NJ', state: 'NJ', zip3: 78, zone: '6b' },
  { city: 'Camden, NJ', state: 'NJ', zip3: 81, zone: '7b' },
  { city: 'Cape May, NJ', state: 'NJ', zip3: 82, zone: '8a' },
  { city: 'Vineland, NJ', state: 'NJ', zip3: 83, zone: '7a' },
  { city: 'Atlantic City, NJ', state: 'NJ', zip3: 84, zone: '8a' },
  { city: 'Trenton, NJ', state: 'NJ', zip3: 86, zone: '7a' },
  // NM
  { city: 'Grants, NM', state: 'NM', zip3: 870, zone: '6a' },
  { city: 'Albuquerque, NM', state: 'NM', zip3: 871, zone: '7b' },
  { city: 'Rio Rancho, NM', state: 'NM', zip3: 871, zone: '7b' },
  { city: 'Gallup, NM', state: 'NM', zip3: 873, zone: '6a' },
  { city: 'Gallup Rural (Zuni), NM', state: 'NM', zip3: 873, zone: '6a' },
  { city: 'Farmington, NM', state: 'NM', zip3: 874, zone: '7a' },
  { city: 'Aztec, NM', state: 'NM', zip3: 874, zone: '6b' },
  { city: 'Santa Fe, NM', state: 'NM', zip3: 875, zone: '6b' },
  { city: 'Los Alamos, NM', state: 'NM', zip3: 875, zone: '7a' },
  { city: 'Taos, NM', state: 'NM', zip3: 875, zone: '5b' },
  { city: 'Red River, NM', state: 'NM', zip3: 875, zone: '5b' },
  { city: 'Angel Fire, NM', state: 'NM', zip3: 875, zone: '5a' },
  { city: 'Espanola, NM', state: 'NM', zip3: 875, zone: '7a' },
  { city: 'Chama, NM', state: 'NM', zip3: 875, zone: '5a' },
  { city: 'Cimarron, NM', state: 'NM', zip3: 876, zone: '6a' },
  { city: 'Las Vegas, NM', state: 'NM', zip3: 877, zone: '6b' },
  { city: 'Raton, NM', state: 'NM', zip3: 877, zone: '6a' },
  { city: 'Socorro, NM', state: 'NM', zip3: 878, zone: '7b' },
  { city: 'Truth or Consequences, NM', state: 'NM', zip3: 879, zone: '8a' },
  { city: 'Las Cruces, NM', state: 'NM', zip3: 880, zone: '8b' },
  { city: 'Silver City, NM', state: 'NM', zip3: 880, zone: '7b' },
  { city: 'Deming, NM', state: 'NM', zip3: 880, zone: '8a' },
  { city: 'Clovis, NM', state: 'NM', zip3: 881, zone: '7a' },
  { city: 'Portales, NM', state: 'NM', zip3: 881, zone: '7a' },
  { city: 'Roswell, NM', state: 'NM', zip3: 882, zone: '7b' },
  { city: 'Carlsbad, NM', state: 'NM', zip3: 882, zone: '8a' },
  { city: 'Alamogordo, NM', state: 'NM', zip3: 883, zone: '8a' },
  { city: 'Cloudcroft, NM', state: 'NM', zip3: 883, zone: '6b' },
  { city: 'Ruidoso, NM', state: 'NM', zip3: 883, zone: '7a' },
  { city: 'Tucumcari, NM', state: 'NM', zip3: 884, zone: '7a' },
  // NV
  { city: 'Henderson, NV', state: 'NV', zip3: 890, zone: '9b' },
  { city: 'Tonopah, NV', state: 'NV', zip3: 890, zone: '7a' },
  { city: 'Pahrump, NV', state: 'NV', zip3: 890, zone: '8b' },
  { city: 'Boulder City, NV', state: 'NV', zip3: 890, zone: '9b' },
  { city: 'Mesquite, NV', state: 'NV', zip3: 890, zone: '9a' },
  { city: 'Las Vegas, NV', state: 'NV', zip3: 891, zone: '9b' },
  { city: 'Ely, NV', state: 'NV', zip3: 893, zone: '5b' },
  { city: 'Sparks, NV', state: 'NV', zip3: 894, zone: '7a' },
  { city: 'Winnemucca, NV', state: 'NV', zip3: 894, zone: '6b' },
  { city: 'Fallon, NV', state: 'NV', zip3: 894, zone: '7a' },
  { city: 'Reno, NV', state: 'NV', zip3: 895, zone: '7b' },
  { city: 'Lake Tahoe (Stateline), NV', state: 'NV', zip3: 895, zone: '7a' },
  { city: 'Carson City, NV', state: 'NV', zip3: 897, zone: '7a' },
  { city: 'Elko, NV', state: 'NV', zip3: 898, zone: '5b' },
  { city: 'Ely-N (Wells), NV', state: 'NV', zip3: 898, zone: '5a' },
  // NY
  { city: 'New York City, NY', state: 'NY', zip3: 100, zone: '7b' },
  { city: 'White Plains, NY', state: 'NY', zip3: 106, zone: '7a' },
  { city: 'Yonkers, NY', state: 'NY', zip3: 107, zone: '7b' },
  { city: 'Brooklyn, NY', state: 'NY', zip3: 112, zone: '7b' },
  { city: 'Long Island (Riverhead), NY', state: 'NY', zip3: 119, zone: '7a' },
  { city: 'Montauk, NY', state: 'NY', zip3: 119, zone: '7b' },
  { city: 'Albany, NY', state: 'NY', zip3: 122, zone: '6a' },
  { city: 'Kingston, NY', state: 'NY', zip3: 124, zone: '6a' },
  { city: 'Catskill, NY', state: 'NY', zip3: 124, zone: '6a' },
  { city: 'Poughkeepsie, NY', state: 'NY', zip3: 126, zone: '6b' },
  { city: 'Glens Falls, NY', state: 'NY', zip3: 128, zone: '5a' },
  { city: 'Lake Placid, NY', state: 'NY', zip3: 129, zone: '4a' },
  { city: 'Saranac Lake, NY', state: 'NY', zip3: 129, zone: '4a' },
  { city: 'Tupper Lake, NY', state: 'NY', zip3: 129, zone: '4a' },
  { city: 'Plattsburgh, NY', state: 'NY', zip3: 129, zone: '5a' },
  { city: 'Malone, NY', state: 'NY', zip3: 129, zone: '5a' },
  { city: 'Syracuse, NY', state: 'NY', zip3: 132, zone: '6a' },
  { city: 'Cooperstown, NY', state: 'NY', zip3: 133, zone: '5b' },
  { city: 'Old Forge, NY', state: 'NY', zip3: 134, zone: '4a' },
  { city: 'Utica, NY', state: 'NY', zip3: 135, zone: '5b' },
  { city: 'Watertown, NY', state: 'NY', zip3: 136, zone: '5a' },
  { city: 'Massena, NY', state: 'NY', zip3: 136, zone: '4b' },
  { city: 'Oneonta, NY', state: 'NY', zip3: 138, zone: '5b' },
  { city: 'Binghamton, NY', state: 'NY', zip3: 139, zone: '6a' },
  { city: 'Buffalo, NY', state: 'NY', zip3: 142, zone: '6b' },
  { city: 'Rochester, NY', state: 'NY', zip3: 146, zone: '6b' },
  { city: 'Jamestown, NY', state: 'NY', zip3: 147, zone: '6a' },
  { city: 'Olean, NY', state: 'NY', zip3: 147, zone: '5b' },
  { city: 'Ithaca, NY', state: 'NY', zip3: 148, zone: '6b' },
  { city: 'Elmira, NY', state: 'NY', zip3: 149, zone: '6a' },
  // OH
  { city: 'Columbus, OH', state: 'OH', zip3: 432, zone: '6b' },
  { city: 'Toledo, OH', state: 'OH', zip3: 436, zone: '6b' },
  { city: 'Cleveland, OH', state: 'OH', zip3: 441, zone: '7a' },
  { city: 'Akron, OH', state: 'OH', zip3: 443, zone: '6b' },
  { city: 'Youngstown, OH', state: 'OH', zip3: 445, zone: '6a' },
  { city: 'Cincinnati, OH', state: 'OH', zip3: 452, zone: '6b' },
  { city: 'Dayton, OH', state: 'OH', zip3: 454, zone: '6b' },
  { city: 'Chillicothe, OH', state: 'OH', zip3: 456, zone: '6b' },
  { city: 'Athens, OH', state: 'OH', zip3: 457, zone: '6b' },
  { city: 'Marietta, OH', state: 'OH', zip3: 457, zone: '6b' },
  // OK
  { city: 'Norman, OK', state: 'OK', zip3: 730, zone: '7b' },
  { city: 'Oklahoma City, OK', state: 'OK', zip3: 731, zone: '7b' },
  { city: 'Ardmore, OK', state: 'OK', zip3: 734, zone: '8a' },
  { city: 'Lawton, OK', state: 'OK', zip3: 735, zone: '7b' },
  { city: 'Enid, OK', state: 'OK', zip3: 737, zone: '7a' },
  { city: 'Woodward, OK', state: 'OK', zip3: 738, zone: '7a' },
  { city: 'Guymon, OK', state: 'OK', zip3: 739, zone: '6b' },
  { city: 'Stillwater, OK', state: 'OK', zip3: 740, zone: '7a' },
  { city: 'Tulsa, OK', state: 'OK', zip3: 741, zone: '7b' },
  { city: 'McAlester, OK', state: 'OK', zip3: 745, zone: '7b' },
  { city: 'Ponca City, OK', state: 'OK', zip3: 746, zone: '7a' },
  { city: 'Broken Bow, OK', state: 'OK', zip3: 747, zone: '8a' },
  // OR
  { city: 'Gresham, OR', state: 'OR', zip3: 970, zone: '9a' },
  { city: 'Hood River, OR', state: 'OR', zip3: 970, zone: '8a' },
  { city: 'The Dalles, OR', state: 'OR', zip3: 970, zone: '8a' },
  { city: 'Government Camp, OR', state: 'OR', zip3: 970, zone: '7b' },
  { city: 'Astoria, OR', state: 'OR', zip3: 971, zone: '9a' },
  { city: 'Tillamook, OR', state: 'OR', zip3: 971, zone: '9a' },
  { city: 'Portland, OR', state: 'OR', zip3: 972, zone: '9a' },
  { city: 'Salem, OR', state: 'OR', zip3: 973, zone: '8b' },
  { city: 'Newport, OR', state: 'OR', zip3: 973, zone: '9b' },
  { city: 'Corvallis, OR', state: 'OR', zip3: 973, zone: '8b' },
  { city: 'Eugene, OR', state: 'OR', zip3: 974, zone: '8b' },
  { city: 'Roseburg, OR', state: 'OR', zip3: 974, zone: '9a' },
  { city: 'Coos Bay, OR', state: 'OR', zip3: 974, zone: '9b' },
  { city: 'Florence, OR', state: 'OR', zip3: 974, zone: '9b' },
  { city: 'Medford, OR', state: 'OR', zip3: 975, zone: '8b' },
  { city: 'Ashland, OR', state: 'OR', zip3: 975, zone: '8a' },
  { city: 'Grants Pass, OR', state: 'OR', zip3: 975, zone: '8b' },
  { city: 'Klamath Falls, OR', state: 'OR', zip3: 976, zone: '6b' },
  { city: 'Lakeview, OR', state: 'OR', zip3: 976, zone: '6b' },
  { city: 'Bend, OR', state: 'OR', zip3: 977, zone: '6b' },
  { city: 'Redmond, OR', state: 'OR', zip3: 977, zone: '6b' },
  { city: 'Sisters, OR', state: 'OR', zip3: 977, zone: '6a' },
  { city: 'Prineville, OR', state: 'OR', zip3: 977, zone: '6b' },
  { city: 'Burns, OR', state: 'OR', zip3: 977, zone: '5b' },
  { city: 'Pendleton, OR', state: 'OR', zip3: 978, zone: '7a' },
  { city: 'La Grande, OR', state: 'OR', zip3: 978, zone: '6b' },
  { city: 'Baker City, OR', state: 'OR', zip3: 978, zone: '6a' },
  { city: 'John Day, OR', state: 'OR', zip3: 978, zone: '6b' },
  { city: 'Enterprise, OR', state: 'OR', zip3: 978, zone: '6a' },
  { city: 'Ontario, OR', state: 'OR', zip3: 979, zone: '7a' },
  // PA
  { city: 'Pittsburgh, PA', state: 'PA', zip3: 152, zone: '6b' },
  { city: 'Somerset, PA', state: 'PA', zip3: 155, zone: '5b' },
  { city: 'Meadville, PA', state: 'PA', zip3: 163, zone: '6a' },
  { city: 'Erie, PA', state: 'PA', zip3: 165, zone: '7a' },
  { city: 'Altoona, PA', state: 'PA', zip3: 166, zone: '6b' },
  { city: 'Bradford, PA', state: 'PA', zip3: 167, zone: '5b' },
  { city: 'State College, PA', state: 'PA', zip3: 168, zone: '6b' },
  { city: 'Wellsboro, PA', state: 'PA', zip3: 169, zone: '5b' },
  { city: 'Harrisburg, PA', state: 'PA', zip3: 171, zone: '7a' },
  { city: 'Chambersburg, PA', state: 'PA', zip3: 172, zone: '7a' },
  { city: 'Lancaster, PA', state: 'PA', zip3: 176, zone: '7a' },
  { city: 'Williamsport, PA', state: 'PA', zip3: 177, zone: '6b' },
  { city: 'Allentown, PA', state: 'PA', zip3: 181, zone: '7a' },
  { city: 'Stroudsburg, PA', state: 'PA', zip3: 183, zone: '6b' },
  { city: 'Scranton, PA', state: 'PA', zip3: 185, zone: '6b' },
  { city: 'Philadelphia, PA', state: 'PA', zip3: 191, zone: '7b' },
  // RI
  { city: 'Newport, RI', state: 'RI', zip3: 28, zone: '7a' },
  { city: 'Warwick, RI', state: 'RI', zip3: 28, zone: '7a' },
  { city: 'Westerly, RI', state: 'RI', zip3: 28, zone: '7a' },
  { city: 'Providence, RI', state: 'RI', zip3: 29, zone: '7a' },
  // SC
  { city: 'Columbia, SC', state: 'SC', zip3: 292, zone: '8b' },
  { city: 'Spartanburg, SC', state: 'SC', zip3: 293, zone: '8a' },
  { city: 'Charleston, SC', state: 'SC', zip3: 294, zone: '9a' },
  { city: 'Myrtle Beach, SC', state: 'SC', zip3: 295, zone: '8b' },
  { city: 'Florence, SC', state: 'SC', zip3: 295, zone: '8b' },
  { city: 'Greenville, SC', state: 'SC', zip3: 296, zone: '8a' },
  { city: 'Walhalla (mountains), SC', state: 'SC', zip3: 296, zone: '8a' },
  { city: 'Rock Hill, SC', state: 'SC', zip3: 297, zone: '8a' },
  { city: 'Aiken, SC', state: 'SC', zip3: 298, zone: '8b' },
  { city: 'Beaufort, SC', state: 'SC', zip3: 299, zone: '9a' },
  // SD
  { city: 'Sioux Falls, SD', state: 'SD', zip3: 571, zone: '5a' },
  { city: 'Watertown, SD', state: 'SD', zip3: 572, zone: '4b' },
  { city: 'Aberdeen, SD', state: 'SD', zip3: 574, zone: '4a' },
  { city: 'Pierre, SD', state: 'SD', zip3: 575, zone: '4b' },
  { city: 'Rapid City, SD', state: 'SD', zip3: 577, zone: '5b' },
  { city: 'Spearfish (Black Hills), SD', state: 'SD', zip3: 577, zone: '5b' },
  // TN
  { city: 'Clarksville, TN', state: 'TN', zip3: 370, zone: '7b' },
  { city: 'Murfreesboro, TN', state: 'TN', zip3: 371, zone: '7b' },
  { city: 'Nashville, TN', state: 'TN', zip3: 372, zone: '7b' },
  { city: 'Cleveland, TN', state: 'TN', zip3: 373, zone: '7b' },
  { city: 'Tullahoma, TN', state: 'TN', zip3: 373, zone: '7b' },
  { city: 'Chattanooga, TN', state: 'TN', zip3: 374, zone: '8a' },
  { city: 'Johnson City, TN', state: 'TN', zip3: 376, zone: '7b' },
  { city: 'Kingsport, TN', state: 'TN', zip3: 376, zone: '7b' },
  { city: 'Bristol, TN', state: 'TN', zip3: 376, zone: '7a' },
  { city: 'Elizabethton, TN', state: 'TN', zip3: 376, zone: '7b' },
  { city: 'Mountain City, TN', state: 'TN', zip3: 376, zone: '6b' },
  { city: 'Gatlinburg, TN', state: 'TN', zip3: 378, zone: '7b' },
  { city: 'Pigeon Forge, TN', state: 'TN', zip3: 378, zone: '7b' },
  { city: 'Knoxville, TN', state: 'TN', zip3: 379, zone: '7b' },
  { city: 'Memphis, TN', state: 'TN', zip3: 381, zone: '8a' },
  { city: 'Jackson, TN', state: 'TN', zip3: 383, zone: '7b' },
  { city: 'Cookeville, TN', state: 'TN', zip3: 385, zone: '7a' },
  { city: 'Crossville, TN', state: 'TN', zip3: 385, zone: '7a' },
  // TX
  { city: 'Sherman, TX', state: 'TX', zip3: 750, zone: '8a' },
  { city: 'Dallas, TX', state: 'TX', zip3: 752, zone: '8b' },
  { city: 'Texarkana, TX', state: 'TX', zip3: 755, zone: '8b' },
  { city: 'Longview, TX', state: 'TX', zip3: 756, zone: '8b' },
  { city: 'Tyler, TX', state: 'TX', zip3: 757, zone: '8b' },
  { city: 'Palestine, TX', state: 'TX', zip3: 758, zone: '8b' },
  { city: 'Fort Worth, TX', state: 'TX', zip3: 761, zone: '8b' },
  { city: 'Wichita Falls, TX', state: 'TX', zip3: 763, zone: '8a' },
  { city: 'Waco, TX', state: 'TX', zip3: 767, zone: '8b' },
  { city: 'San Angelo, TX', state: 'TX', zip3: 769, zone: '8a' },
  { city: 'Houston, TX', state: 'TX', zip3: 770, zone: '9b' },
  { city: 'Galveston, TX', state: 'TX', zip3: 775, zone: '10a' },
  { city: 'Beaumont, TX', state: 'TX', zip3: 777, zone: '9b' },
  { city: 'Victoria, TX', state: 'TX', zip3: 779, zone: '9b' },
  { city: 'Laredo, TX', state: 'TX', zip3: 780, zone: '9b' },
  { city: 'Kerrville, TX', state: 'TX', zip3: 780, zone: '8b' },
  { city: 'San Antonio, TX', state: 'TX', zip3: 782, zone: '9a' },
  { city: 'Corpus Christi, TX', state: 'TX', zip3: 784, zone: '10a' },
  { city: 'Brownsville, TX', state: 'TX', zip3: 785, zone: '10a' },
  { city: 'McAllen, TX', state: 'TX', zip3: 785, zone: '10a' },
  { city: 'Fredericksburg, TX', state: 'TX', zip3: 786, zone: '8b' },
  { city: 'Austin, TX', state: 'TX', zip3: 787, zone: '9a' },
  { city: 'Del Rio, TX', state: 'TX', zip3: 788, zone: '9a' },
  { city: 'Uvalde, TX', state: 'TX', zip3: 788, zone: '9a' },
  { city: 'Amarillo, TX', state: 'TX', zip3: 791, zone: '7a' },
  { city: 'Lubbock, TX', state: 'TX', zip3: 794, zone: '7b' },
  { city: 'Abilene, TX', state: 'TX', zip3: 796, zone: '8a' },
  { city: 'Midland, TX', state: 'TX', zip3: 797, zone: '8b' },
  { city: 'Odessa, TX', state: 'TX', zip3: 797, zone: '8b' },
  { city: 'Alpine, TX', state: 'TX', zip3: 798, zone: '8a' },
  { city: 'Big Bend (Marfa), TX', state: 'TX', zip3: 798, zone: '8a' },
  { city: 'El Paso, TX', state: 'TX', zip3: 799, zone: '8b' },
  // UT
  { city: 'Park City, UT', state: 'UT', zip3: 840, zone: '5b' },
  { city: 'Orem, UT', state: 'UT', zip3: 840, zone: '7a' },
  { city: 'Heber City, UT', state: 'UT', zip3: 840, zone: '6a' },
  { city: 'Vernal, UT', state: 'UT', zip3: 840, zone: '6a' },
  { city: 'Roosevelt, UT', state: 'UT', zip3: 840, zone: '5b' },
  { city: 'Tooele, UT', state: 'UT', zip3: 840, zone: '7a' },
  { city: 'Duchesne, UT', state: 'UT', zip3: 840, zone: '6a' },
  { city: 'Salt Lake City, UT', state: 'UT', zip3: 841, zone: '7b' },
  { city: 'West Valley City, UT', state: 'UT', zip3: 841, zone: '7b' },
  { city: 'Logan, UT', state: 'UT', zip3: 843, zone: '6a' },
  { city: 'Brigham City, UT', state: 'UT', zip3: 843, zone: '6b' },
  { city: 'Tremonton, UT', state: 'UT', zip3: 843, zone: '6b' },
  { city: 'Ogden, UT', state: 'UT', zip3: 844, zone: '7a' },
  { city: 'Price, UT', state: 'UT', zip3: 845, zone: '6b' },
  { city: 'Moab, UT', state: 'UT', zip3: 845, zone: '7b' },
  { city: 'Green River, UT', state: 'UT', zip3: 845, zone: '6b' },
  { city: 'Monticello, UT', state: 'UT', zip3: 845, zone: '6a' },
  { city: 'Blanding, UT', state: 'UT', zip3: 845, zone: '7a' },
  { city: 'Provo, UT', state: 'UT', zip3: 846, zone: '7a' },
  { city: 'Delta, UT', state: 'UT', zip3: 846, zone: '6a' },
  { city: 'Fillmore, UT', state: 'UT', zip3: 846, zone: '6b' },
  { city: 'Nephi, UT', state: 'UT', zip3: 846, zone: '6b' },
  { city: 'Richfield, UT', state: 'UT', zip3: 847, zone: '6a' },
  { city: 'Cedar City, UT', state: 'UT', zip3: 847, zone: '6b' },
  { city: 'St. George, UT', state: 'UT', zip3: 847, zone: '8b' },
  { city: 'Kanab, UT', state: 'UT', zip3: 847, zone: '7a' },
  { city: 'Bryce Canyon (Panguitch), UT', state: 'UT', zip3: 847, zone: '5b' },
  { city: 'Beaver, UT', state: 'UT', zip3: 847, zone: '6a' },
  { city: 'Escalante, UT', state: 'UT', zip3: 847, zone: '7a' },
  { city: 'Milford, UT', state: 'UT', zip3: 847, zone: '6a' },
  // VA
  { city: 'Arlington, VA', state: 'VA', zip3: 222, zone: '7b' },
  { city: 'Alexandria, VA', state: 'VA', zip3: 223, zone: '8a' },
  { city: 'Fredericksburg, VA', state: 'VA', zip3: 224, zone: '7b' },
  { city: 'Winchester, VA', state: 'VA', zip3: 226, zone: '7a' },
  { city: 'Front Royal, VA', state: 'VA', zip3: 226, zone: '7a' },
  { city: 'Harrisonburg, VA', state: 'VA', zip3: 228, zone: '7a' },
  { city: 'Charlottesville, VA', state: 'VA', zip3: 229, zone: '7b' },
  { city: 'Richmond, VA', state: 'VA', zip3: 232, zone: '7b' },
  { city: 'Virginia Beach, VA', state: 'VA', zip3: 234, zone: '8b' },
  { city: 'Norfolk, VA', state: 'VA', zip3: 235, zone: '8b' },
  { city: 'Roanoke, VA', state: 'VA', zip3: 240, zone: '7b' },
  { city: 'Blacksburg, VA', state: 'VA', zip3: 240, zone: '7a' },
  { city: 'Abingdon, VA', state: 'VA', zip3: 242, zone: '7a' },
  { city: 'Bristol, VA', state: 'VA', zip3: 242, zone: '7a' },
  { city: 'Wytheville, VA', state: 'VA', zip3: 243, zone: '7a' },
  { city: 'Marion, VA', state: 'VA', zip3: 243, zone: '7a' },
  { city: 'Staunton, VA', state: 'VA', zip3: 244, zone: '7a' },
  { city: 'Lynchburg, VA', state: 'VA', zip3: 245, zone: '7b' },
  { city: 'Danville, VA', state: 'VA', zip3: 245, zone: '7b' },
  { city: 'Big Stone Gap, VA', state: 'VA', zip3: 246, zone: '7a' },
  // VT
  { city: 'Manchester, VT', state: 'VT', zip3: 52, zone: '5b' },
  { city: 'Bennington, VT', state: 'VT', zip3: 52, zone: '5b' },
  { city: 'Brattleboro, VT', state: 'VT', zip3: 53, zone: '6a' },
  { city: 'Burlington, VT', state: 'VT', zip3: 54, zone: '5a' },
  { city: 'Montpelier, VT', state: 'VT', zip3: 56, zone: '4b' },
  { city: 'Stowe, VT', state: 'VT', zip3: 56, zone: '4b' },
  { city: 'Rutland, VT', state: 'VT', zip3: 57, zone: '5a' },
  { city: 'Killington, VT', state: 'VT', zip3: 57, zone: '5a' },
  { city: 'Middlebury, VT', state: 'VT', zip3: 57, zone: '5a' },
  { city: 'St. Johnsbury, VT', state: 'VT', zip3: 58, zone: '4b' },
  { city: 'Newport, VT', state: 'VT', zip3: 58, zone: '4b' },
  { city: 'Jay Peak (Jay), VT', state: 'VT', zip3: 58, zone: '5a' },
  // WA
  { city: 'Bellevue, WA', state: 'WA', zip3: 980, zone: '9a' },
  { city: 'North Bend, WA', state: 'WA', zip3: 980, zone: '8b' },
  { city: 'Snoqualmie Pass, WA', state: 'WA', zip3: 980, zone: '7b' },
  { city: 'Seattle, WA', state: 'WA', zip3: 981, zone: '9a' },
  { city: 'Everett, WA', state: 'WA', zip3: 982, zone: '8b' },
  { city: 'Bellingham, WA', state: 'WA', zip3: 982, zone: '8b' },
  { city: 'Mount Vernon, WA', state: 'WA', zip3: 982, zone: '8b' },
  { city: 'Stevens Pass, WA', state: 'WA', zip3: 982, zone: '7a' },
  { city: 'Port Angeles, WA', state: 'WA', zip3: 983, zone: '9a' },
  { city: 'Forks, WA', state: 'WA', zip3: 983, zone: '9a' },
  { city: 'Mount Rainier (Ashford), WA', state: 'WA', zip3: 983, zone: '8a' },
  { city: 'Tacoma, WA', state: 'WA', zip3: 984, zone: '8b' },
  { city: 'Olympia, WA', state: 'WA', zip3: 985, zone: '8b' },
  { city: 'Aberdeen, WA', state: 'WA', zip3: 985, zone: '9a' },
  { city: 'Shelton, WA', state: 'WA', zip3: 985, zone: '8b' },
  { city: 'Vancouver, WA', state: 'WA', zip3: 986, zone: '8b' },
  { city: 'Longview, WA', state: 'WA', zip3: 986, zone: '8b' },
  { city: 'Goldendale, WA', state: 'WA', zip3: 986, zone: '7a' },
  { city: 'Wenatchee, WA', state: 'WA', zip3: 988, zone: '7b' },
  { city: 'Leavenworth, WA', state: 'WA', zip3: 988, zone: '7a' },
  { city: 'Chelan, WA', state: 'WA', zip3: 988, zone: '7b' },
  { city: 'Okanogan, WA', state: 'WA', zip3: 988, zone: '7a' },
  { city: 'Winthrop, WA', state: 'WA', zip3: 988, zone: '5b' },
  { city: 'Twisp, WA', state: 'WA', zip3: 988, zone: '6a' },
  { city: 'Yakima, WA', state: 'WA', zip3: 989, zone: '7a' },
  { city: 'Ellensburg, WA', state: 'WA', zip3: 989, zone: '6b' },
  { city: 'Cle Elum, WA', state: 'WA', zip3: 989, zone: '7a' },
  { city: 'Spokane Rural (Colville), WA', state: 'WA', zip3: 991, zone: '6b' },
  { city: 'Republic, WA', state: 'WA', zip3: 991, zone: '6a' },
  { city: 'Pullman, WA', state: 'WA', zip3: 991, zone: '6b' },
  { city: 'Spokane, WA', state: 'WA', zip3: 992, zone: '7a' },
  { city: 'Spokane Valley, WA', state: 'WA', zip3: 992, zone: '7a' },
  { city: 'Walla Walla, WA', state: 'WA', zip3: 993, zone: '7b' },
  { city: 'Pasco, WA', state: 'WA', zip3: 993, zone: '7b' },
  { city: 'Richland, WA', state: 'WA', zip3: 993, zone: '7b' },
  // WI
  { city: 'Kenosha, WI', state: 'WI', zip3: 531, zone: '6a' },
  { city: 'Milwaukee, WI', state: 'WI', zip3: 532, zone: '6a' },
  { city: 'Madison, WI', state: 'WI', zip3: 537, zone: '5a' },
  { city: 'Door County (Sturgeon Bay), WI', state: 'WI', zip3: 542, zone: '5b' },
  { city: 'Green Bay, WI', state: 'WI', zip3: 543, zone: '5b' },
  { city: 'Wausau, WI', state: 'WI', zip3: 544, zone: '5a' },
  { city: 'Wisconsin Rapids, WI', state: 'WI', zip3: 544, zone: '4b' },
  { city: 'Rhinelander, WI', state: 'WI', zip3: 545, zone: '4a' },
  { city: 'Minocqua, WI', state: 'WI', zip3: 545, zone: '4a' },
  { city: 'La Crosse, WI', state: 'WI', zip3: 546, zone: '5a' },
  { city: 'Eau Claire, WI', state: 'WI', zip3: 547, zone: '4b' },
  { city: 'Superior, WI', state: 'WI', zip3: 548, zone: '5a' },
  // WV
  { city: 'Bluefield, WV', state: 'WV', zip3: 247, zone: '7a' },
  { city: 'Welch, WV', state: 'WV', zip3: 248, zone: '7a' },
  { city: 'Lewisburg, WV', state: 'WV', zip3: 249, zone: '6b' },
  { city: 'Charleston, WV', state: 'WV', zip3: 253, zone: '7a' },
  { city: 'Martinsburg, WV', state: 'WV', zip3: 254, zone: '7a' },
  { city: 'Huntington, WV', state: 'WV', zip3: 257, zone: '7a' },
  { city: 'Beckley, WV', state: 'WV', zip3: 258, zone: '7a' },
  { city: 'Wheeling, WV', state: 'WV', zip3: 260, zone: '6b' },
  { city: 'Parkersburg, WV', state: 'WV', zip3: 261, zone: '6b' },
  { city: 'Elkins, WV', state: 'WV', zip3: 262, zone: '6a' },
  { city: 'Snowshoe, WV', state: 'WV', zip3: 262, zone: '6a' },
  { city: 'Weston, WV', state: 'WV', zip3: 264, zone: '6b' },
  { city: 'Morgantown, WV', state: 'WV', zip3: 265, zone: '6b' },
  { city: 'Summersville, WV', state: 'WV', zip3: 266, zone: '6b' },
  { city: 'Davis, WV', state: 'WV', zip3: 267, zone: '6a' },
  { city: 'Petersburg, WV', state: 'WV', zip3: 268, zone: '7a' },
  // WY
  { city: 'Cheyenne, WY', state: 'WY', zip3: 820, zone: '5b' },
  { city: 'Laramie, WY', state: 'WY', zip3: 820, zone: '4a' },
  { city: 'Torrington, WY', state: 'WY', zip3: 822, zone: '5a' },
  { city: 'Rawlins, WY', state: 'WY', zip3: 823, zone: '5a' },
  { city: 'Cody, WY', state: 'WY', zip3: 824, zone: '5a' },
  { city: 'Worland, WY', state: 'WY', zip3: 824, zone: '4b' },
  { city: 'Powell, WY', state: 'WY', zip3: 824, zone: '5a' },
  { city: 'Yellowstone (Cody-N), WY', state: 'WY', zip3: 824, zone: '4a' },
  { city: 'Riverton, WY', state: 'WY', zip3: 825, zone: '4b' },
  { city: 'Lander, WY', state: 'WY', zip3: 825, zone: '5a' },
  { city: 'Casper, WY', state: 'WY', zip3: 826, zone: '5a' },
  { city: 'Douglas, WY', state: 'WY', zip3: 826, zone: '4b' },
  { city: 'Gillette, WY', state: 'WY', zip3: 827, zone: '5a' },
  { city: 'Newcastle, WY', state: 'WY', zip3: 827, zone: '5a' },
  { city: 'Sheridan, WY', state: 'WY', zip3: 828, zone: '4b' },
  { city: 'Buffalo, WY', state: 'WY', zip3: 828, zone: '5a' },
  { city: 'Rock Springs, WY', state: 'WY', zip3: 829, zone: '5a' },
  { city: 'Evanston, WY', state: 'WY', zip3: 829, zone: '5a' },
  { city: 'Pinedale, WY', state: 'WY', zip3: 829, zone: '4a' },
  { city: 'Jackson, WY', state: 'WY', zip3: 830, zone: '4b' },
  // AK, HI — outside the ArcGIS 2023 layer's 48-state coverage; kept as
  // single verified reference points per the original data (see note below).
  { city: 'Anchorage, AK', state: 'AK', zip3: 995, zone: '5a' },
  { city: 'Honolulu, HI', state: 'HI', zip3: 968, zone: '12b' },
];

export function findZoneForZip(zip: string): { zone: string; refCity: string } | null {
  if (zip.length !== 5) return null;
  const zip3 = parseInt(zip.slice(0, 3), 10);
  if (!Number.isFinite(zip3)) return null;

  const range = ZIP3_TO_STATE.find((r) => zip3 >= r.start && zip3 <= r.end);
  if (!range) return null;

  const candidates = REFERENCE_CITIES.filter((c) => c.state === range.state);
  if (candidates.length === 0) return null;

  let best = candidates[0];
  let bestDist = Math.abs(candidates[0].zip3 - zip3);
  for (const c of candidates.slice(1)) {
    const dist = Math.abs(c.zip3 - zip3);
    if (dist < bestDist) {
      best = c;
      bestDist = dist;
    }
  }
  return { zone: best.zone, refCity: best.city };
}

// ---------------------------------------------------------------------------
// Zone -> frost date range data. Ranges (not single dates) are used
// deliberately: these are general USDA-hardiness-zone-based approximations,
// not station-level climate normals. Actual dates for any specific location
// can vary from these ranges by one to several weeks depending on elevation,
// urban heat island effect, distance from water, and other microclimate
// factors.
// ---------------------------------------------------------------------------
export interface ZoneFrostData {
  lastFrostStart: [number, number]; // [month(0-11), day]
  lastFrostEnd: [number, number];
  firstFrostStart: [number, number];
  firstFrostEnd: [number, number];
  frostFree?: boolean;
}

// Center dates for zones 3, 5, 8, 9, and 10 are anchored directly to the
// commonly-cited zone-level frost date approximations (May 15/Sep 15 for
// zone 3, Apr 15/Oct 15 for zone 5, Mar 15/Nov 15 for zone 8, Feb 15/Dec 15
// for zone 9, and ~Jan 31 for zone 10 — the same figures widely published by
// seed companies and extension-adjacent gardening references). Zones 2, 4, 6,
// and 7 are linearly interpolated between those anchors rather than copied
// flatly, since frost timing genuinely shifts zone-to-zone even where the
// coarse public tables round several zones to the same figure. Each date is
// then shown as a +/- 7 day window, not a single point, to reflect real
// year-to-year variability at the zone level.
export const ZONE_FROST_DATA: Record<string, ZoneFrostData> = {
  '2': { lastFrostStart: [4, 23], lastFrostEnd: [5, 6], firstFrostStart: [7, 24], firstFrostEnd: [8, 7] },
  '3': { lastFrostStart: [4, 8], lastFrostEnd: [4, 22], firstFrostStart: [8, 8], firstFrostEnd: [8, 22] },
  '4': { lastFrostStart: [3, 23], lastFrostEnd: [4, 7], firstFrostStart: [8, 23], firstFrostEnd: [9, 7] },
  '5': { lastFrostStart: [3, 8], lastFrostEnd: [3, 22], firstFrostStart: [9, 8], firstFrostEnd: [9, 22] },
  '6': { lastFrostStart: [2, 29], lastFrostEnd: [3, 12], firstFrostStart: [9, 18], firstFrostEnd: [10, 1] },
  '7': { lastFrostStart: [2, 18], lastFrostEnd: [3, 1], firstFrostStart: [9, 29], firstFrostEnd: [10, 12] },
  '8': { lastFrostStart: [2, 8], lastFrostEnd: [2, 22], firstFrostStart: [10, 8], firstFrostEnd: [10, 22] },
  '9': { lastFrostStart: [1, 8], lastFrostEnd: [1, 22], firstFrostStart: [11, 8], firstFrostEnd: [11, 22] },
  '10': { lastFrostStart: [0, 24], lastFrostEnd: [1, 7], firstFrostStart: [11, 24], firstFrostEnd: [0, 7], frostFree: true },
  '11': { lastFrostStart: [0, 1], lastFrostEnd: [0, 1], firstFrostStart: [11, 31], firstFrostEnd: [11, 31], frostFree: true },
  '12': { lastFrostStart: [0, 1], lastFrostEnd: [0, 1], firstFrostStart: [11, 31], firstFrostEnd: [11, 31], frostFree: true },
  '13': { lastFrostStart: [0, 1], lastFrostEnd: [0, 1], firstFrostStart: [11, 31], firstFrostEnd: [11, 31], frostFree: true },
};

export const ALL_ZONES = [
  '2a', '2b', '3a', '3b', '4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b',
  '8a', '8b', '9a', '9b', '10a', '10b', '11a', '11b', '12a', '12b', '13a', '13b',
];

export const REF_YEAR = 2027; // arbitrary non-leap reference year; only month/day are ever displayed

export function mkDate(md: [number, number]): Date {
  return new Date(REF_YEAR, md[0], md[1]);
}

export function shiftWeeks(date: Date, weeks: number): Date {
  const d = new Date(date);
  d.setDate(d.getDate() + Math.round(weeks * 7));
  return d;
}

export function fmtDate(date: Date): string {
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

export function daysBetween(a: Date, b: Date): number {
  const msPerDay = 1000 * 60 * 60 * 24;
  return Math.round((b.getTime() - a.getTime()) / msPerDay);
}

export function midpoint(a: Date, b: Date): Date {
  return new Date((a.getTime() + b.getTime()) / 2);
}

export function sanitizeZip(raw: string): string {
  if (typeof raw !== 'string') return '';
  return raw.replace(/[^\d]/g, '').slice(0, 5);
}

export function fullZoneNumberFromZone(zone: string | null): string | null {
  if (!zone) return null;
  const match = zone.match(/^(\d+)/);
  return match ? match[1] : null;
}
