/*
 * One import surface for the ported data.
 *
 * Every file beside this one is generated by scripts/port-data.mjs and carries
 * a banner saying so. This file is written by hand and is the only one here
 * that is: it exists so the rest of the app imports `@ported` rather than
 * reaching into individual generated files, which means regenerating them
 * cannot break an import path.
 */
export * from './companion.ts'
export * from './zones.ts'
export * from './zoneTemps.ts'
export * from './potsize.ts'
export * from './diagnosis.ts'
export * from './toxicity.ts'
